---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    kubevirt.io: ""
  name: boxes.doslab.io
spec:
  group: doslab.io
  names:
    kind: Box
    plural: boxes
    shortNames:
    - box
    - boxes
    singular: box
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
    additionalPrinterColumns:
    - jsonPath: .spec.nodeName
      name: NODE
      type: string
